name: App Setup

on:
  push:
    branches:
      - main
      - develop
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Start Ubuntu and Install Go
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget
          wget https://go.dev/dl/go1.23.3.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.23.3.linux-amd64.tar.gz
          echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc
          source ~/.bashrc

      - name: Verify Go Installation
        run: go version
